# Generated by Django 5.0.3 on 2024-04-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relevant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='city',
            field=models.CharField(default='city', max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(default='m', max_length=1),
        ),
    ]
